# NOTE: Types and Input Types are defined in classes

type Query {
    ticketCategories: [TicketCategory!]!
    ticketCategoryById(id: Int): TicketCategory
    passengers: [Passenger!]!
    passengerById(id: Long): Passenger
    ticketTypes: [TicketType!]!
    ticketTypeById(id: Int): TicketType
    userCards: [UserCard!]!
    userCardById(id: Int): UserCard
    transactions: [Transaction!]!
    transactionById(id: String): Transaction
    tickets: [Ticket!]!
    ticketById(id: String): Ticket
}

type Mutation {
    saveTicketCategory(ticketCategory: TicketCategoryInput): TicketCategory
    deleteTicketCategory(id: Int!): Boolean
    savePassenger(passenger: PassengerInput): Passenger
    deletePassenger(id: Int!): Boolean
    saveTicketType(ticketType: TicketTypeInput): TicketType
    deleteTicketType(id: Int!): Boolean
    saveUserCard(userCard: UserCardInput): UserCard
    deleteUserCard(id: Int!): Boolean
    saveTransaction(transaction: TransactionInput): Transaction
    deleteTransaction(id: String!): Boolean
    saveTicket(ticket: TicketInput): Ticket
    deleteTicket(id: String!): Boolean
}